#
# Makefile for tfa9891 smartamp driver.
#

#debugging support (also enables trace_printk)
#CFLAGS += -DDEBUG
#CFLAGS += -Werror

snd-soc-tfa98xx-objs += tfa98xx.o
snd-soc-tfa98xx-objs += tfa_container.o
snd-soc-tfa98xx-objs += tfa_dsp.o
snd-soc-tfa98xx-objs += tfa9888_init.o
snd-soc-tfa98xx-objs += tfa9891_init.o
snd-soc-tfa98xx-objs += tfa9897_init.o
snd-soc-tfa98xx-objs += tfa9890_init.o
snd-soc-tfa98xx-objs += tfa9887B_init.o
snd-soc-tfa98xx-objs += tfa9887_init.o
snd-soc-tfa98xx-objs += tfa_debug.o

obj-$(CONFIG_SND_SOC_TFA9891) += snd-soc-tfa98xx.o
